version: '3'

services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    volumes:
      - ./backend:/var/ounass/backend

    networks:
      - nginx_network

  frontend:
    build: ./frontend
    container_name: frontend
    command: [ "npm", "start" ]
    volumes:
      - ./frontend/:/var/ounass/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - nginx_network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/ounass/log/nginx
      - ./frontend:/var/ounass/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - nginx_network


networks:
  nginx_network:
    driver: bridge